### ISSUE TITLE
Trouble with load on startup (desktop)

### ISSUE THREAD

**Issue by Didkrak** [edave64/Doki-Doki-Dialog-Generator#27]
This looks like an annoying issue, not a dialog-breaking one though. The "load on startup" option for content packs is not working for me since installing version 2.3. Uninstalling and reinstalling version 2.2 does not fix this though, so it is not solely a version 2.3 thing.

The load on startup option is remembered between sessions, I can change it then close and reopen and the change is saved. I tried backing up and deleting the cache/local storage/etc. by deleting the "AppData\Roaming\dddg-desktop-version" folder as well as uninstalling and reinstalling, but this only further complicated things. The "load on startup" options were all cleared and they would still save between sessions, but if I used the option for any character's "styles" then the character would not be in the "add character" tool anymore on the next startup. I have to deactivate the packs for the character to show up again. Except every once in awhile, around 1 in every 15 startup attempts, it will load up properly, with the character available and the content packs activated. I haven't noticed anything would cause that difference. Just constantly opening and closing the dialog maker occasionally has the character loaded, usually doesn't.

This isn't happening in the browser version (load on startup is working fine on it), and it happens for both the "default" content packs and added ones, and whether the packs are saved locally or not. Does the dialog maker use any other folders/settings so I can do a full uninstall and see if that fixes things?

**Comment by edave64** [comment]
Could you do two debugging steps for me?

First, go to "%LOCALAPPDATA%\Programs\dddg-desktop-version", and run the "Doki Doki Dialog Generator.exe" using the console. Please attach the contents of the console.

Second, in DDDG, on a failed load, press CTRL+SHIFT+I to open the debugging tools and go to the tab "Console", Please attach the contents of that.

Watch out to remove potential identifying information, like your windows username, from those logs.

I already have a part of the code under suspicion, but I'd like to see if there are any issues visible there.

**Comment by Didkrak** [comment]
Finally finished the CD I was working on and can do this testing.

I get no output from the console when I start the generator through it. Or any reaction at all really, save a new console window opening, with the usual newly opened console output (windows version and copyright notice).

I've also tried recreating the problem to get info from the debugging tools, but it seems to have fixed itself somehow... Load on startup is working perfectly now, with no failures after over a dozen attempts. Restarting the PC doesn't bring the problem back either. I'd guess it was somehow related to the new install, and something the generator did during use fixed it, but to test that I'd have to do a reinstall to see if that brings back the problem.

**Comment by edave64** [comment]
I think the latest release should fix this issue. At least, it fixed a similar issue for another user
