### ISSUE TITLE
Download Links

### ISSUE THREAD

**Issue by SteveeWasTaken** [edave64/Doki-Doki-Dialog-Generator#30]
It seems like Desktop download links were deleted, because the tag v1.5 has a file [docs/desktop.md](https://github.com/edave64/Doki-Doki-Dialog-Generator/blob/v1.5/docs/desktop.md) and there are download links for DDDG. However, recent versions don't have the docs/desktop.md file, and don't seem to have any way of downloading the program at all. How can I download the latest version?

**Comment by edave64** [comment]
The desktop version was moved to its own project. Thanks for the reminder that I might need to update the documentation again, since I now know that at least one person has read it :P

https://github.com/edave64/dddg-desktop-version/releases

**Comment by SteveeWasTaken** [comment]
I think it'd be nice if you could tell users exactly that, so that they know where to find the program. Thanks though!

**Comment by edave64** [comment]
I didn't update the docs yet, but I linked the deskop release page in the readme
