### ISSUE TITLE
problem with loading the whole thing

### ISSUE THREAD

**Issue by dancingdolphin1231** [edave64/Doki-Doki-Dialog-Generator#46]
so i go into doki doki dialog generator, and its not loading any, i mean the logo on my tab is showing, and the network for me is on... not to mention that it also isn't loading the characters, the backgrounds, no NOTHING! I also reloaded the tab millions of times, and it still doesn't work. any suggestions on how to fix this problem?

**Comment by dancingdolphin1231** [comment]
it also isn't loading the characters, the backgrounds, no NOTHING!

**Comment by edave64** [comment]
@dancingdolphin1231 Nothing recently changed with the dialog generator. Did you close it because it worked again? If so, I guess there was just some hiccup with the hosting
